//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rytasoft.CustomerSupport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderItem
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderItem { get; set; }
    }
}
